#!/bin/bash
#h-------------------------------------------------------------------------------
#h
#h Name:         constants
#h Type:         Linux shell script
#h Purpose:      sets RRDTool_API constants
#h Project:      
#h Usage:        #set path constants
#h               . `dirname $(readlink -f $0)`/00_constants
#h Result:       
#h Examples:     
#h Outline:      
#h Resources:    
#h Platforms:    Linux
#h Authors:      peb piet66
#h Version:      V1.0.0 2023-01-02/peb
#v History:      V1.0.0 2022-11-20/peb first version
#h Copyright:    (C) piet66 2022
#h License:      MIT
#h
#h-------------------------------------------------------------------------------

MODULE='constants';
VERSION='V1.0.0'
WRITTEN='2023-01-02/peb'

PACKET_NAME=RRDTool_API
PACKET_PATH=`dirname $(readlink -f $0)`
PACKET_DIR=`basename $PACKET_PATH`
echo PACKET_NAME=$PACKET_NAME
echo PACKET_PATH=$PACKET_PATH
echo PACKET_DIR=$PACKET_DIR
cd $PACKET_PATH

PORT=5001
echo PORT=$PORT

#create packet folders
GRAPHS_IMG=./graphs_img
mkdir -pv $GRAPHS_IMG
GRAPHS_DEF=./graphs_def
mkdir -pv $GRAPHS_DEF
HTML=./html
mkdir -pv $HTML/img
RRD=./rrd
mkdir -pv $RRD

LOG_DIR=log
LOG_PATH=$PACKET_PATH/$LOG_DIR
echo LOG_PATH=$LOG_PATH
mkdir -pv $LOG_PATH
echo ''

# python virtual environment
VIRTUAL_ENV=$PACKET_PATH/__python_env__
echo VIRTUAL_ENV=$VIRTUAL_ENV
if [ -d "$VIRTUAL_ENV" ]
then
    echo source $VIRTUAL_ENV/bin/activate
    source $VIRTUAL_ENV/bin/activate
    pip3 -V
fi
echo ''

